---
repo-name: peripherals-zoom
categories:
- Video Communications
display-name: Zoom
manufacturer: Zoom 
product: Zoom
description: Zoom provides videotelephony and online chat services through a cloud-based peer-to-peer software platform and is used for teleconferencing, telecommuting, distance education, and social relations.